- app/Config/Cache.php
- app/Config/Filters.php
- app/Config/Format.php
- app/Config/Images.php
- app/Config/Toolbar.php
- app/Config/Validation.php
- app/Controllers/BaseController.php
- public/index.php
Updates framework files to their latest (using `Tatter\Patches`).
> Patch to framework latest

- app/Config/Cache.php
- composer.lock
- public/index.php
- spark
* Patches project files to framework `4.1.3`
* Updates all dependencies
> Patch to latest

- app/Config/Database.php
- app/Config/DocTypes.php
- app/Config/Email.php
- app/Config/Encryption.php
- app/Config/Honeypot.php
- app/Config/Kint.php
- app/Config/Migrations.php
- app/Config/Pager.php
- app/Config/Paths.php
- app/Config/UserAgents.php
- app/Config/View.php
- app/Controllers/BaseController.php
- app/Controllers/Home.php
- composer.lock
* Updates project files to their `4.1.3` equivalent
* Updates all dependencies
> Patch to 4.1.3

- public/assets/css/ci-theme.css
The version number was on the left due to a small mistake. I fixed it.
> Update Spotlight Codeigniter Version Number

- .github/workflows/test.yml
- app/Config/Services.php
This PR makes token failures more explicit and includes the secret under CI.
> GitHub Access Token

- .github/workflows/deduplicate.yml
- .github/workflows/inspect.yml
- .github/workflows/test.yml
- .php-cs-fixer.dist.php
- README.md
- SECURITY.md
- composer.json
- composer.lock
- depfile.yaml
- phpunit.xml.dist
* Switches `Psr\Cache` to the new stable release
* Refreshes testing workflows
* Switches to CodeIgniter Coding Standard with PHP CS Fixer and NexusPHP CS Config (not yet applied)
> Development Update

- app/Config/Blog.php
- app/Config/Kint.php
- app/Entities/GitHub/Release.php
- app/Entities/GitHub/Repo.php
- app/Models/MyBBModel.php
Some new rules in the CodeIgniter Coding Standard result in some small changes here.
> Coding Standard

- .github/workflows/deduplicate.yml
- .github/workflows/test.yml
- .github/workflows/unused.yml
- composer.json
- composer.lock
- depfile.yaml
- phpstan.neon.dist
* Fixes a few small issues with CI/CD workflows
* Adds "Composer Unused" to prohibit cruft packages
> Toolkit Improvements

- app/Config/GitHub.php
- app/Config/Services.php
- app/Controllers/Download.php
- app/Libraries/GitHub.php
- tests/libaries/GitHubTest.php
https://codeigniter.com/download
> Fix latest release version

- public/assets/css/ci-responsive.css
There were some mobile screen issues which I came across on Iphone.
> Update upon release

- public/assets/css/ci-theme.css
Regarding the points underlined in the forum, I have also added class option for content-outer and inner.
> Adding Class Options

- app/Views/home.php
- public/assets/css/ci-theme.css
https://github.com/codeigniter4projects/website/issues/148
> change git icons to svg

- app/Views/home.php
- public/assets/css/ci-theme.css
https://github.com/codeigniter4projects/website/issues/151
> update important links section icons

- app/Views/download.php
- app/Views/policies.php
https://github.com/codeigniter4projects/website/issues/156
> fix html output

- app/Views/home.php
- public/assets/css/ci-theme.css
https://github.com/codeigniter4projects/website/issues/158
> update "Why CodeIgniter?" section icons

- public/assets/css/ci-responsive.css
https://github.com/codeigniter4projects/website/issues/167
after fix
> fix news column on tablet

- public/assets/css/ci-responsive.css
https://github.com/codeigniter4projects/website/issues/162
Tablet
Mobile
> fix intro logotype on tablet & mobile

- public/assets/css/ci-responsive.css
https://github.com/codeigniter4projects/website/issues/171
after fix
> fix toggle menu btn

- public/assets/css/ci-responsive.css
https://github.com/codeigniter4projects/website/issues/173
> update icon links on mobile

- public/assets/css/ci-responsive.css
- public/assets/css/ci-theme.css
https://github.com/codeigniter4projects/website/issues/178
> update download page

- app/Views/layouts/_footer.php
https://github.com/codeigniter4projects/website/issues/183
> Accessibility - add alt to img

- app/Views/layouts/_footer.php
https://github.com/codeigniter4projects/website/issues/185
> Accessibility - add link name

- app/Views/contribute.php
resolve https://github.com/codeigniter4projects/website/issues/190
> Accessibility - add alt to img (contribute page)

- app/Views/fine_print.php
https://github.com/codeigniter4projects/website/issues/196
cc @MGatner
> Accessibility - add alt to img (print page)

- app/Views/policies.php
https://github.com/codeigniter4projects/website/issues/194
> Accessibility - add alt to img (policies page)

- public/assets/css/ci-responsive.css
resolve https://github.com/codeigniter4projects/website/issues/198
> important links fix on 1280px

- app/Controllers/Download.php
resolve https://github.com/codeigniter4projects/website/issues/203
> update download link

- public/assets/css/ci-responsive.css
reslove https://github.com/codeigniter4projects/website/issues/205
made to fit more content on mobile devices
> update container on mobile

- public/assets/css/ci-responsive.css
resolve https://github.com/codeigniter4projects/website/issues/226
> fix news code on mobile

- public/assets/css/ci-responsive.css
https://github.com/codeigniter4projects/website/issues/230
> fix menu on resize

- public/assets/css/ci-responsive.css
resolve https://github.com/codeigniter4projects/website/issues/239
after fix
> add more "air" to footer logo on mobile (ui)

- public/favicons/site.webmanifest
https://github.com/codeigniter4projects/website/issues/252
> minor update webmanifest

- app/Views/download.php
- make it clear that CI4 supports PHP 8.1
> Update PHP version to 8.1 in download page

- .editorconfig
- app/Config/App.php
- app/Config/Constants.php
- app/Config/ContentSecurityPolicy.php
- app/Config/Database.php
- app/Config/Feature.php
- app/Config/Filters.php
- app/Config/Format.php
- app/Config/Logger.php
- app/Config/Mimes.php
- app/Config/Publisher.php
- app/Config/Routes.php
- app/Config/Security.php
- app/Config/Toolbar.php
- app/Config/Validation.php
- app/Config/View.php
- app/Controllers/BaseController.php
- app/Views/errors/html/debug.css
- app/Views/errors/html/debug.js
- app/Views/errors/html/error_404.php
- app/Views/errors/html/error_exception.php
- app/Views/errors/html/production.php
- app/index.html
- composer.lock
- env
- public/index.php
- spark
* Updates framework files to `4.2.0`
* Updates and applies latest DevKit templates
> Apply Patches

- public/assets/css/ci-theme.css
pre areas are highlighted now,
Left column width and heading styles of the left column are arranged.
> Blog & News Page

- app/Views/layouts/_footer.php
resolve https://github.com/codeigniter4projects/website/issues/208
> remove dependabot

- app/Config/App.php
This should be addressed at the server level as well but for now this will redirect insecure traffic.
Fixes #316
> Enforce HTTPS

- app/Common.php
- app/Entities/GitHub/Release.php
- app/Libraries/Blog.php
- app/Views/errors/html/error_exception.php
- composer.lock
* Updates framework to 4.2.10
* Patches project files to latest equivalent
* ~~Bumps all minor dependencies~~
Supersedes #328
> Patch framework to 4.2.10

- app/Config/GitHub.php
- app/Controllers/Home.php
> fix: GitHub Star & Fork count

- public/assets/css/ci-theme.css
resolve https://github.com/codeigniter4projects/website/issues/327
> make github scores font size bigger

- app/Config/Constants.php
resolve https://github.com/codeigniter4projects/website/issues/334
> update app folder links

- .editorconfig
resolve https://github.com/codeigniter4projects/website/issues/341
> update root folder links

- app/Views/layouts/_footer.php
See
- https://security.snyk.io/package/npm/jquery
- https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/
- https://jquery.com/upgrade-guide/3.5/
- https://blog.jquery.com/2021/03/02/jquery-3-6-0-released/
> chore: update jQuery to 3.6.2

- app/Views/layouts/_footer.php
> chore: update jQuery to 3.6.3

- README.md
> docs: add missing forceGlobalSecureRequests in README

- public/assets/css/ci-responsive.css
- public/assets/css/ci-theme.css
Supersedes #390
See the diff https://github.com/codeigniter4projects/website/pull/395/files?w=1
> Dark mode fixes

- public/assets/css/ci-theme.css
resolve https://github.com/codeigniter4projects/website/issues/405
> fix github icon dark theme

- public/assets/css/ci-responsive.css
- public/assets/css/ci-theme.css
Hi there, 
There were a few problems with some colors such as Clear Documentation icon, dark theme box title and also some others on responsive side such as mobile menu icon.
> Fixing Some Colors

- .github/scripts/deploy.sh
- .github/workflows/deploy.yml
Follow-up #439
- add uid check. To avoid accidentally running as root
- fix syntax for echo
- add fingerprint check
> chore: improve deploy workflow

- composer.json
- composer.lock
- tests/libaries/GitHubTest.php
- update composer.json
- update Composer packages
- fix coding-standard version for PHPUnit9
- fix test code for PHPStan
> chore: update composer.json
